In [1]:
# statistical function of Numpy

In [2]:
import numpy as np
test_scores = np.array([32.32,56.87,87.87,96.72])
test_scores

array([32.32, 56.87, 87.87, 96.72])

In [3]:
# mean of the test_scores

In [4]:
print('mean test_scores of the students:')
print(np.mean(test_scores))

mean test_score of the students:
68.445


In [5]:
print('median test_scores of the student:')
print(np.median(test_scores))

median test_scores of the student:
72.37


In [6]:
print('mode test_scores of the students:')
print(np.mode(test_scores))

mode test_scores of the students:


AttributeError: module 'numpy' has no attribute 'mode'

In [7]:
# standard Deviation

In [11]:
print('sd of the test_scores:')
print(np.std(test_scores))

sd of the test_scores:
25.572458329225995


In [ ]:
# iteration Of numpy

In [12]:
a =np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [13]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [22]:
import numpy as np
students = np.array([['Bhagya','Saritha','Aishwarya','Dorcus'],
                    [65,78,98,45],
                    [56,88,99,57]])

In [24]:
students.ndim # Multi dimension iteration

2

In [28]:
for i in students:
    print('i=',i)

i= ['Bhagya' 'Saritha' 'Aishwarya' 'Dorcus']
i= ['65' '78' '98' '45']
i= ['56' '88' '99' '57']


In [ ]:
# splitt each and every element Row wise

In [29]:
for x in students.flatten():
    print(x)

Bhagya
Saritha
Aishwarya
Dorcus
65
78
98
45
56
88
99
57


In [ ]:
# split each and every element Coloum wise

In [31]:
for y in students.flatten(order='F'): # F Is Forton Ordering method
    print(y)

Bhagya
65
56
Saritha
78
88
Aishwarya
98
99
Dorcus
45
57


In [ ]:
# Alternative approach to flatten

In [33]:
x =np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
for x in np.nditer(x): # Row wise Splitting
    print(x)

0
1
2
3
4
5
6
7
8


In [37]:
for abc in np.nditer(abc,order ='F'):
    print(abc)

57


In [38]:
for y in np.nditer(y,order='F'):
    print(y)

57


In [40]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
for i in np.nditer(i,order = 'F'):
    print(i)

57
